on:
  push:
    branches: main

name: Render site

jobs:
  render:
    name: Render site
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("tidyverse")'
      - name: Install DT
        run: Rscript -e 'install.packages("DT")'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("index.Rmd")'
      - name: Commit results
        run: |
          git commit index.html -m 'Re-build index.html' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
